### ISSUE TITLE
why do you use ZeroMQ

### ISSUE THREAD

**Issue by fizz12344321** [izherebkin/SpringZeroMQSandbox#2]
hi, I am reading your project, why do you use ZeroMQ in your project instead of other message queues like Kafka, RabbitMQ... can you tell me about your purpose, the cons and pros of ZeroMQ, thank you so much

**Comment by izherebkin** [comment]
Hi! This repository was created as a sandbox and playground over ZeroMQ. This approach has been used in other commercial projects. And above all for these projects, the advantages of ZeroMQ are as follows:

- High-performance asynchronous messaging library like Kafka, RabbitMQ
- ZeroMQ can run without a dedicated message broker, it is brokerless, but Kafka, RabbitMQ don't
- ZeroMQ has CurveZMQ, a protocol for secure messaging across the Internet, and all you need to enable it, just define private and public keys, thats all, and all your messages are encrypted. In Kafka, RabbitMQ, it will be more difficult to implement similar.
